spring:
  profiles:
    active: dev
  application:
    name: app-version-manager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
debug: true
server:
  servlet:
    context-path: /manager
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
logging:
  level:
    com.tairanchina: debug